{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "efcf368c",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "import pandas as pd\n",
    "\n",
    "import numpy as np\n",
    "import scipy\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from operator import itemgetter\n",
    "from azure.ai.textanalytics import TextAnalyticsClient\n",
    "from azure.core.credentials import AzureKeyCredential\n",
    "\n",
    "\n",
    "class Topic_determination:\n",
    "    \n",
    "    def __init__(self):\n",
    "        self.df_topics= None\n",
    "        self.df = None\n",
    "        \n",
    "    def run(self, df, top_n=1, clustered_by=\"ssdsLemma\",categorize_key=None):\n",
    "        \n",
    "        \n",
    "        \"\"\"\n",
    "            Takes the Dataframe from Clustering, and returns, enriched by the\n",
    "            topics of \n",
    "            \n",
    "            \n",
    "            \n",
    "        \"\"\"\n",
    "        df_top=group_by_cluster(df,col_name)\n",
    "        df_top=return_topics(df_top,top_n,col_name)\n",
    "        if(categorize_key==True):\n",
    "            df_top=cetegorize_text(df_top,key)\n",
    "        df_res=topics_to_service(df,df_top,col_name)\n",
    "        return df_res\n",
    "        \n",
    "        \n",
    "    def group_by_cluster(df,col_name=\"ssdsLemma\"):\n",
    "        df_work = df[[f\"{col_name}_processed\",f\"{col_name}_cluster\"]]\n",
    "        df_work=df_work.groupby([f\"{col_name}_cluster\"])[f\"{col_name}_processed\"].apply(lambda x: ' '.join(x)).reset_index()\n",
    "        return df_work\n",
    "    \n",
    "    def return_topics(df,n=1,col_name=\"ssdsLemma\"):\n",
    "        vectorizer=TfidfVectorizer()\n",
    "        rows = vectorizer.fit_transform(df[f\"{col_name}_processed\"].tolist()).toarray()\n",
    "        features=vectorizer.get_feature_names()\n",
    "        i=0\n",
    "        topics=[]\n",
    "        while i<len(rows):\n",
    "            top_feats=[]\n",
    "            topn_ids = np.argsort(rows[i])[::-1][:n]\n",
    "            top_feats = [(features[j]) for j in topn_ids]\n",
    "            topics.append(top_feats)\n",
    "            i+=1\n",
    "        df['Topics']=topics\n",
    "        return df\n",
    "    \n",
    "    def topics_to_service(df_res,df_clus,col_name=\"ssdsLemma\"):\n",
    "        df_res[\"Topics\"]=df_res.apply(lambda row: df_clus.iloc[df_res[f\"{col_name}_cluster\"].iloc[row.name],2], axis=1)\n",
    "        if 'categorized' in df_clus:\n",
    "            df_res[\"categorized\"]=df_res.apply(lambda row: df_clus.iloc[df_res[f\"{col_name}_cluster\"].iloc[row.name],3], axis=1)\n",
    "        return df_res\n",
    "    \n",
    "    def categorize_text(df,key,endpoint=\"https://berlinbobbi.cognitiveservices.azure.com/\",col_name=\"ssdsLemma\"):\n",
    "        client=authenticate_azure_client(key,endpoint)\n",
    "        topic=[None]*len(df)\n",
    "        i=0\n",
    "        while i<len(df):            \n",
    "            documents=[df[f\"{col_name}_processed\"].iloc[i][0:5119]]    \n",
    "            result =client.recognize_entities(documents)[0]\n",
    "            summary=[]       \n",
    "            for entity in result.entities:\n",
    "                categorized=[entity.text,entity.category,round(entity.confidence_score,2),entity.offset]\n",
    "                summary.append(categorized)\n",
    "            topic[i]=(sorted(summary,key=itemgetter(3),reverse=False))\n",
    "            i+=1\n",
    "        df['categorized']=topic\n",
    "        return df                       \n",
    "                   \n",
    "    def authenticate_azure_client(key,endpoint=\"https://berlinbobbi.cognitiveservices.azure.com/\"):\n",
    "        ta_credential = AzureKeyCredential(key)\n",
    "        text_analytics_client = TextAnalyticsClient(endpoint=endpoint, \n",
    "        credential=ta_credential)\n",
    "        return text_analytics_client\n",
    "    \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "39d36808",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
